// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFigZR2c5XskhEMYAbUS5B3MeWMJWKmY8',
    appId: '1:91031806639:web:51d4b30f7bfb66da742a5a',
    messagingSenderId: '91031806639',
    projectId: 'phone-auth-cc5a8',
    authDomain: 'phone-auth-cc5a8.firebaseapp.com',
    storageBucket: 'phone-auth-cc5a8.appspot.com',
    measurementId: 'G-T1ECCDR5WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARhGV3Yckxduxjqc9d4dWjzRDvncmLoXw',
    appId: '1:91031806639:android:6287b90e59cf8d9c742a5a',
    messagingSenderId: '91031806639',
    projectId: 'phone-auth-cc5a8',
    storageBucket: 'phone-auth-cc5a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuRIm37ixxVSZkWG4niAPBgEA9MBXBEjs',
    appId: '1:91031806639:ios:e0c90a987d06b711742a5a',
    messagingSenderId: '91031806639',
    projectId: 'phone-auth-cc5a8',
    storageBucket: 'phone-auth-cc5a8.appspot.com',
    androidClientId: '91031806639-qcp577ft648ktob3ceptsutuhf5n3qou.apps.googleusercontent.com',
    iosClientId: '91031806639-5kqvsaact75v2cd0c5lnolbac9i7odd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPhoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuRIm37ixxVSZkWG4niAPBgEA9MBXBEjs',
    appId: '1:91031806639:ios:e0c90a987d06b711742a5a',
    messagingSenderId: '91031806639',
    projectId: 'phone-auth-cc5a8',
    storageBucket: 'phone-auth-cc5a8.appspot.com',
    androidClientId: '91031806639-qcp577ft648ktob3ceptsutuhf5n3qou.apps.googleusercontent.com',
    iosClientId: '91031806639-5kqvsaact75v2cd0c5lnolbac9i7odd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPhoneAuth',
  );
}
